---
- name: test ansible-vault with keyring
  hosts: control
  gather_facts: false
 

  tasks:
    - name: raw result of running date command"
      debug:
        # msg: "{{ lookup('pipe', './get_pass.py') }}"
        msg: "{{ lookup('community.general.keyring', 'test test') }}"

...
