---
- name: lookup password and pipe it to stout
  hosts: control
  gather_facts: false
  # collections:
  #   - community.general

  tasks:
    - name: test pipe lookup plugin
      debug:
        # msg: "{{ lookup('pipe', './get_pass.sh') }}"
        # msg: "{{ lookup('pipe', './get_pass.py') }}"
        msg: "{{ lookup('pipe', './vault-keyring.py') }}"

...
