---
- name: lookup password and pipe it to stout
  hosts: control
  gather_facts: false
  collections:
    - community.general

  tasks:
    - name: raw result of running date command"
      debug:
        # msg: "{{ lookup('pipe', './get_pass.sh') }}"
        msg: "{{ lookup('pipe', './get_pass.py') }}"
...
